/* Do not edit, autogenerated */

#pragma once

#define AEC_MAX_Y_CHANNELS         (2)
#define AEC_MAX_X_CHANNELS         (2)
#define AEC_MAIN_FILTER_PHASES     (10)
#define AEC_SHADOW_FILTER_PHASES   (5)
