/* Do not edit, autogenerated */

#pragma once

#define AEC_THREAD_COUNT   1
#define AEC_3_TASKS_AND_CHANNELS_PASSES   (6)
#define AEC_2_TASKS_AND_CHANNELS_PASSES   (4)
#define AEC_1_TASKS_AND_CHANNELS_PASSES   (2)
#define AEC_2_TASKS_PASSES   (2)
#define AEC_3_TASKS_PASSES   (3)

typedef struct {
    int task;
    int channel;
    int is_active;
} par_tasks_and_channels_t;

typedef struct {
    int task;
    int is_active;
} par_tasks_t;

typedef struct {
    par_tasks_and_channels_t par_3_tasks_and_channels[AEC_THREAD_COUNT][AEC_3_TASKS_AND_CHANNELS_PASSES];
    par_tasks_and_channels_t par_2_tasks_and_channels[AEC_THREAD_COUNT][AEC_2_TASKS_AND_CHANNELS_PASSES];
    par_tasks_and_channels_t par_1_tasks_and_channels[AEC_THREAD_COUNT][AEC_1_TASKS_AND_CHANNELS_PASSES];
    par_tasks_t par_2_tasks[AEC_THREAD_COUNT][AEC_2_TASKS_PASSES];
    par_tasks_t par_3_tasks[AEC_THREAD_COUNT][AEC_3_TASKS_PASSES];
} task_distribution_t;
